# This is a basic workflow to help you get started with Actions

name: testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print status for job1
        run: echo "Job1 is running"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print status for job2
        run: echo "Job2 is running"

  get-workflow-status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get workflow status
        run: |
          echo "Fetching workflow status..."
          curl -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
               | jq '.conclusion'
