# This is a basic workflow to help you get started with Actions

name: testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print status for job1
        run: echo "Job1 is running"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: fail the job
        run: exit 1

      - name: Print status for job2
        run: echo ${{job.status}}

  job3: 
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
    steps:
      - name: Dump GitHub context
        env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"
    

  
